[project]
name = "pydparser-assessment"
version = "0.1.0"
description = "Custom parsing logic for NLP playground."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
pydparser-assessment = "pydparser_assessment.__main__:main"

[tool.uv]
